dev:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: ["/bin/bash", "--rcfile", "/opt/gypsy/venv/bin/activate"]
test:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/run_tests.sh'
docs:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/make_docs.sh'
lint:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/lint.sh'
pre-commit:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash git-hooks/pre-commit.sh'
