dev:
  container_name: gypsy
  build: .
  env_file: env/dev.env
  volumes:
    - ./:/opt/gypsy
  command: ["/bin/bash", "--rcfile", "/opt/gypsy/venv/bin/activate"]
test:
  container_name: gypsy
  build: .
  env_file: env/dev.env
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/run_tests.sh'
docs:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/make_docs.sh'
lint:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/lint.sh'
pre-commit:
  container_name: gypsy
  build: .
  volumes:
    - ./:/opt/gypsy
  command: 'bash bin/run_pylint_commit_hook.sh'
